version: "3.8"

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./reports:/app/reports
    environment:
      - NODE_ENV=test
      - API_URL=${API_URL:-http://localhost:3000}
      - API_VERSION=${API_VERSION:-v1}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1h}
    networks:
      - test-network

  # Optional: Add a mock API service if needed for local development
  # mock-api:
  #   image: node:20-slim
  #   working_dir: /app
  #   volumes:
  #     - ./mock-api:/app
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - test-network

networks:
  test-network:
    driver: bridge
